services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: students
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
