services:
  backend:
    container_name: backend
    image: backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/students?schema=public
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: students
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
